[package]
name = "gdbserver"
version = "0.1.0"
authors = ["jD91mZM2 <me@krake.one>"]
edition = "2018"

[dependencies]
# gdb-remote-protocol = { git = "https://github.com/luser/rust-gdb-remote-protocol" }
gdb-remote-protocol = { path = "../external/rust-gdb-remote-protocol/" }
structopt = "0.2.18"
memchr = "2.2.1"
libc = "0.2.62"
